# Generated by Django 2.1.4 on 2019-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
