# Generated by Django 2.1.4 on 2019-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='app.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
