# Generated by Django 2.1.4 on 2019-04-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190429_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('product', models.ManyToManyField(blank=True, null=True, to='app.Product')),
            ],
        ),
    ]
