# Generated by Django 2.1.4 on 2019-04-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190429_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
