# Generated by Django 2.1.4 on 2019-04-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190429_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='app.Product'),
        ),
    ]
