# Generated by Django 2.1.4 on 2019-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190429_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
