# Generated by Django 2.1.4 on 2019-04-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190429_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
