# Generated by Django 2.1.4 on 2019-04-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190429_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
