# Generated by Django 2.1.4 on 2019-04-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190429_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
