# Generated by Django 2.1.4 on 2019-04-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190429_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
