# Generated by Django 2.1.4 on 2019-05-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190430_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
