# Generated by Django 2.1.4 on 2019-05-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190501_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
